### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by HelenaKschidock** [precice/dumux-adapter#21]
https://github.com/precice/dumux-adapter/blob/9249ec2dce400bf4dd28c4abf6760d71838e4aca/README.md?plain=1#L68

I think this should be

```
./dune-common/bin/dunecontrol --only=dumux-adapter/dumux-precice all 
```
(Dumux-precice is a directory, not an opts file).

**Comment by IshaanDesai** [comment]
Yes, makes sense. I will fix this directly on develop.

**Comment by mathiskelm** [comment]
The dune.module file is actually in dumux-adapter, so one should use that for --only.

**Comment by mathiskelm** [comment]
Actually, we have to pass just the module name, `dumux-precice`. The location will be found by dunecontrol. Sadly the bahaviour/output of dunecontrol when using the `--only` option is a little confusing.

**Comment by IshaanDesai** [comment]
> Actually, we have to pass just the module name, `dumux-precice`. The location will be found by dunecontrol. Sadly the bahaviour/output of dunecontrol when using the `--only` option is a little confusing.

Thanks for the info Mathis! Passing only the module name does indeed work. Is the change from `--opts` to `--only` clear?

**Comment by mathiskelm** [comment]
> > Actually, we have to pass just the module name, `dumux-precice`. The location will be found by dunecontrol. Sadly the bahaviour/output of dunecontrol when using the `--only` option is a little confusing.
> 
> Thanks for the info Mathis! Passing only the module name does indeed work. Is the change from `--opts` to `--only` clear?

I agree that it was likely intended to be `--only` rather than `--opts`, yes. Just have to also change the value of the option.

I don't think additionally using something like `--opts=dumux/cmake.opts` in the instructions is necessary.
