### ISSUE TITLE
Distinct `preice::string_view`s when implicitly constructing from `std::string` or literal

### ISSUE THREAD

**Issue by mathiskelm** [precice/dumux-adapter#28]
## Description

Several interfaces of the `CouplingAdapter` such as `announceQuantity` and `getQuantityVector` use the new `precice::string_view` after the port to `precice:develop` / preCICEv3. One can pass also `std::string`s or "string"-literals, which are then converted. As literals such as `"dataName"` are `\0`-terminated `char[]`, their size is 1 greater than the string and they produce a different `string_view`.

`std::string("dataName")` seems to be compatible with `precice::string_view("dataName", 8)` while `"dataName"` produces `precice::string_view("dataName", 9)`.

This currently allows to announce the same quantity twice, since the adapter checks whether the `string_view` has already been announced (false) and preCICE seems to view them both as equal to the name registered in the preCICE config file.

### Environment

Ubuntu 22.04 LTS, preCICE:develop, DuMuX 3.8, DuMuX-preCICE:develop

## Steps to reproduce

Announce a quantity twice, using once a `std::string` and once a literal

### Expected behavior

If passing a `std::string` and literal are allowed, they should refer to the same quantity.

### Actual behavior

Depending on how the string_view is created, the quantities are treated as distinct.

**Comment by fsimonis** [comment]
You noticed an implementation detail of using the `string_views` in the API.

While you are correct that the literal contain the NULL byte, preCICE handles this internally.
In `src/precice/Participant.cpp`, we convert all `precice::string_views` to `std::string_view` before passing them `ParticipantImpl`.

This step removes the NULL byte and everything past it from given string_views.
